package moderation

// defaultBlocklist contains blocked terms organized by category.
// Single words are matched against individual tokens (word-boundary aware).
// Multi-word phrases are matched as substrings in the normalized message.
//
// This is a starter list (~120 terms) intended to be expanded over time.
// Categories: slurs/hate speech, harassment, adult content, doxxing/PII,
// spam, and threats/violence.
var defaultBlocklist = []string{
	// --- Slurs and hate speech ---
	"nigger",
	"nigga",
	"niggers",
	"niggas",
	"faggot",
	"faggots",
	"fag",
	"fags",
	"dyke",
	"dykes",
	"tranny",
	"trannies",
	"retard",
	"retards",
	"retarded",
	"spic",
	"spics",
	"wetback",
	"wetbacks",
	"kike",
	"kikes",
	"chink",
	"chinks",
	"gook",
	"gooks",
	"beaner",
	"beaners",
	"coon",
	"coons",
	"raghead",
	"ragheads",
	"towelhead",
	"towelheads",
	"cracker",
	"zipperhead",

	// --- Harassment phrases ---
	"kill yourself",
	"kys",
	"go die",
	"drink bleach",
	"hang yourself",
	"neck yourself",
	"end yourself",
	"slit your wrists",
	"nobody loves you",
	"you should die",
	"hope you die",
	"get raped",
	"i will find you",
	"i know where you live",

	// --- Adult / explicit content ---
	"cum slut",
	"cock whore",
	"child porn",
	"kiddie porn",
	"cp links",
	"jailbait",
	"lolicon",
	"shotacon",
	"underage sex",
	"pedo",
	"pedophile",
	"pedophilia",
	"molest",
	"molestation",
	"incest",
	"bestiality",
	"zoophilia",
	"snuff",
	"rape porn",
	"revenge porn",

	// --- Doxxing / PII solicitation ---
	"send me your address",
	"what is your address",
	"whats your address",
	"where do you live",
	"send your ssn",
	"social security number",
	"credit card number",
	"send nudes",
	"send me nudes",
	"show me your body",
	"how old are you really",
	"are you underage",

	// --- Spam and scam ---
	"buy followers",
	"free bitcoin",
	"free crypto",
	"double your money",
	"nigerian prince",
	"wire transfer",
	"click this link",
	"earn money fast",
	"make money online",
	"hot singles",
	"onlyfans link",

	// --- Threats and violence ---
	"i will kill you",
	"i will murder you",
	"gonna shoot up",
	"school shooting",
	"bomb threat",
	"swatting",
	"swat you",
	"dox you",
	"doxxing you",
	"leaked your info",
	"gonna stab you",
	"curb stomp",

	// --- Extremism ---
	"heil hitler",
	"sieg heil",
	"white power",
	"white supremacy",
	"race war",
	"ethnic cleansing",
	"gas the",
	"genocide",
	"join isis",
	"allahu akbar bomb",
}
